---

- name: ensure tasks run only on selected os releases
  block:

    - name: "add {{ vimrc_label }} {{ vimrc_type }}(s) to vimrc generator"
      ansible.builtin.blockinfile:
        path: "{{ vimrc_script }}"
        insertafter: "### {{ vimrc_type }}s ###"
        marker: "### {mark} {{ vimrc_label }} {{ vimrc_type }}s ###"
        block: "{{ vimrc_content }}"
      when: >
        vimrc_type == "script" or
        vimrc_type == "variable"

  when: ansible_distribution == "Fedora"

...
