---

- name: ensure tasks run only on selected os releases
  block:

    - name: initialize vimrc generator
      ansible.builtin.template:
        src: vim_configurator.sh.j2
        dest: "{{ vimrc_script }}"
        force: false
        owner: root
        group: root
        mode: "0644"

  when: ansible_distribution == "Fedora"

...
